### ISSUE TITLE
Upload build artifacts in actions

### ISSUE THREAD

**Issue by p1x3l101-10** [alegian/thavma#12]
Could you modify the workflow file to upload an artifact of the compiled mod?

**Comment by alegian** [comment]
Im not entire sure how to do that yet. I will have to look at some other mod to understand how that works and where the upload goes

**Comment by p1x3l101-10** [comment]
In my own repo, I use something like this:
```
    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Bundles
        path: |
          curseforge.zip
          prismlauncher.zip
```
However, I do not know where Thaumva builds to.
